version: 2.1
orbs: 
  rust: circleci/rust@1.6.0
node: &node
  working_directory: ~/project
  docker:
  - image: cimg/node:current
  resource_class: medium
default: &default
  working_directory: ~/project
  docker:
  - image: cimg/rust:1.61
  environment:
    CARGO_TERM_COLOR: always
    # Fail the build if there are warnings
    RUSTFLAGS: '-D warnings'
default_medium: &default_medium
  working_directory: ~/project
  docker:
  - image: cimg/rust:1.61
  environment:
    CARGO_TERM_COLOR: always
    # Fail the build if there are warnings
    RUSTFLAGS: '-D warnings'
  resource_class: medium

commands:
  restore_node_module_cache:
    steps:
    - restore_cache:
        name: Restoring node_module cache
        keys:
          - package-lock-v1-{{ checksum "package-lock.json" }}
          - package-lock-v1-
  save_node_module_cache:
    steps:
    - save_cache:
        name: Saving node_module cache
        key: package-lock-v1-{{ checksum "package-lock.json" }}
        paths:
        - ~/.npm
  restore_rustup_cache:
    steps:
    - restore_cache:
        name: Restoring rustup cache
        keys:
          - rust-v1-{{ checksum "rust-toolchain.toml" }}
          - rust-v1-
  save_rustup_cache:
    steps:
    - save_cache:
        name: Saving rustup cache
        key: rust-v1-{{ checksum "rust-toolchain.toml" }}
        paths:
        - ~/.rustup
  restore_cargo_cache:
    steps:
    - restore_cache:
        name: Restoring cargo registry cache
        keys:
          - cargo-lock-v2-{{ checksum "Cargo.lock" }}
          - cargo-lock-v2-
  save_cargo_cache:
    steps:
    - save_cache:
        name: Saving cargo cache
        key: cargo-lock-v2-{{ checksum "Cargo.lock" }}
        paths:
          - ~/.cargo/registry

jobs:
  setup:
    <<: *node
    steps:
    - checkout
    - restore_node_module_cache
    - run:
        name: Install dependencies
        command: npm install
    - save_node_module_cache
    - persist_to_workspace:
        root: ~/project
        paths:
        - node_modules

  install_rust:
    <<: *default_medium
    steps:
    - checkout
    - restore_rustup_cache
    - run:
        name: Show rustup home
        command: rustup show home
    - run:
        name: Show and install selected toolchain
        command: rustup show
    - save_rustup_cache
    - restore_cargo_cache
    - run:
        name: Download dependencies
        command: cargo fetch
    - save_cargo_cache


  lint_commit_message:
    <<: *node
    steps:
    - checkout
    - attach_workspace:
        at: ~/project
    - run:
        name: Define environment variable with lastest commit's message
        command: |
          echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Lint commit message
        command: echo "$COMMIT_MESSAGE" | npx commitlint
    
  test:
    <<: *default
    steps:
    - checkout
    - run:
        name: Install nextest
        command: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-$HOME/.cargo}/bin
    - run:
        name: Install circleci-junit-fix
        command: |
          mkdir -p ~/.local/bin
          curl -sSL https://github.com/conradludgate/circleci-junit-fix/releases/download/v0.1.0/circleci-junit-fix-v0.1.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=$HOME/.local/bin
    - restore_cargo_cache
    - restore_rustup_cache
    - run:
        name: Run tests
        command: cargo nextest run --profile ci
    - run:
        name: Preprocess JUnit file
        command: cat target/nextest/ci/junit.xml | circleci-junit-fix > fixed-report.xml
    - store_test_results:
        path: fixed-report.xml
    
  format:
    <<: *default_medium
    steps:
    - checkout
    - restore_cargo_cache
    - restore_rustup_cache
    - run:
        name: Run rustfmt
        command: cargo fmt -- --check
    
  clippy:
    <<: *default
    steps:
    - checkout
    - restore_cargo_cache
    - restore_rustup_cache
    - run:
        name: Run Clippy
        command: cargo clippy
    
  build:
    <<: *default
    steps:
    - checkout
    - restore_cargo_cache
    - restore_rustup_cache
    - run:
        name: Build binary
        command: cargo build --release
  
  pants:
    <<: *default_medium
    steps:
    - checkout
    - restore_cache:
        name: Restoring cargo pants cache
        keys:
          - v1-cargo-pants-{{ checksum "~/.cargo/bin/cargo-pants" }}
          - v1-cargo-pants-
    - run:
        name: Install tools
        command: cargo install cargo-pants
    - save_cache:
        name: Saving cargo pants cache
        key: v1-cargo-pants-{{ checksum "~/.cargo/bin/cargo-pants" }}
        paths:
          - ~/.cargo
    - run:
        name: Run cargo pants
        command: cargo pants --louds
  

workflows:
  version: 2
  commit:
    jobs:
    - setup
    - install_rust
    - lint_commit_message: { requires: [setup] }
    - test: { requires: [install_rust] }
    - format: { requires: [install_rust] }
    - clippy: { requires: [install_rust] }
    - build: { requires: [install_rust] }
    - pants: { requires: [install_rust] }
  
