version: 2.1
orbs: 
  rust: circleci/rust@1.6.0
default: &default
  working_directory: ~/project
  docker:
  - image: cimg/rust:1.61-node

jobs:
  setup:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: package-lock-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: package-lock-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - persist_to_workspace:
        root: ~/project
        paths:
        - node_modules

  lint_commit_message:
    <<: *default
    steps:
    - checkout
    - attach_workspace:
        at: ~/project
    - run:
        name: Define environment variable with lastest commit's message
        command: |
          echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Lint commit message
        command: echo "$COMMIT_MESSAGE" | npx commitlint
    
  test:
    <<: *default
    steps:
    - checkout
    - run:
        name: Install nextest
        command: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - restore_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
    - run:
        name: Run tests
        command: cargo nextest run --profile ci
    - save_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
        paths:
          - /usr/local/cargo/registry
          - target/debug/.fingerprint
          - target/debug/build
          - target/debug/deps

workflows:
  version: 2
  commit:
    jobs:
    - setup
    - lint_commit_message: { requires: [setup] }
    - test
  
