version: 2.1
orbs: 
  rust: circleci/rust@1.6.0
default: &default
  working_directory: ~/project
  docker:
  - image: cimg/rust:1.61-node

jobs:
  setup:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: package-lock-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: package-lock-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - persist_to_workspace:
        root: ~/project
        paths:
        - node_modules

  install_nightly_rust:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
    - run:
        name: Show rustup home
        command: rustup show home
    - run:
        name: Install nightly Rust
        command: rustup update
    - save_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
        paths:
        - /root/.rustup

  lint_commit_message:
    <<: *default
    steps:
    - checkout
    - attach_workspace:
        at: ~/project
    - run:
        name: Define environment variable with lastest commit's message
        command: |
          echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Lint commit message
        command: echo "$COMMIT_MESSAGE" | npx commitlint
    
  test:
    <<: *default
    steps:
    - checkout
    - run:
        name: Install nextest
        command: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - restore_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
    - restore_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
    - run:
        name: Run tests
        command: cargo nextest run --profile ci
    - save_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
        paths:
          - ~/.cargo
    
  format:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
    - restore_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
    - run:
        name: Run rustfmt
        command: cargo fmt -- --check
    - save_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
        paths:
          - ~/.cargo
    
  clippy:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
    - restore_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
    - run:
        name: Run Clippy
        command: cargo clippy
    - save_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
        paths:
          - ~/.cargo
    
  build-release:
    <<: *default
    steps:
    - checkout
    - restore_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
    - restore_cache:
        key: rust-{{ checksum "rust-toolchain.toml" }}
    - run:
        name: Build in release mode
        command: cargo build --release
    - save_cache:
        key: cargo-lock-{{ checksum "Cargo.lock" }}
        paths:
          - ~/.cargo
        

workflows:
  version: 2
  commit:
    jobs:
    - setup
    - lint_commit_message: { requires: [setup] }
    - test: { requires: [install_nightly_rust] }
    - format: { requires: [install_nightly_rust] }
    - clippy: { requires: [install_nightly_rust] }
    - build-release: { requires: [install_nightly_rust] }
  
